#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sdoc
Version  : 0.4.1
Release  : 6
URL      : https://rubygems.org/downloads/sdoc-0.4.1.gem
Source0  : https://rubygems.org/downloads/sdoc-0.4.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-sdoc-bin
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
Patch1: 0001-Fix-minitest-version.patch

%description
# SDoc
[![Build Status](https://travis-ci.org/zzak/sdoc.png?branch=master)](https://travis-ci.org/zzak/sdoc)

%package bin
Summary: bin components for the rubygem-sdoc package.
Group: Binaries

%description bin
bin components for the rubygem-sdoc package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sdoc-0.4.1
gem spec %{SOURCE0} -l --ruby > rubygem-sdoc.gemspec
%patch1 -p1

%build
gem build rubygem-sdoc.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sdoc-0.4.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/sdoc-0.4.1 && rake --trace test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/sdoc-0.4.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/Gem/Specification/cdesc-Specification.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/Gem/cdesc-Gem.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/AnyMethod/cdesc-AnyMethod.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/AnyMethod/sdoc_markup_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/ClassModule/cdesc-ClassModule.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/ClassModule/with_documentation%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/FilesTree/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/FilesTree/cdesc-FilesTree.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/FilesTree/children-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/add_class_search_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/add_file_search_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/add_method_search_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/base_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/cdesc-SDoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/class_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/copy_resources-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/debug_msg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/file_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_class_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_class_tree-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_class_tree_level-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_file_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_file_tree-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_file_tree_level-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_index_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/generate_search_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/index_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/setup_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/SDoc/store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Generator/cdesc-Generator.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Options/github-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/Options/search_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/RDoc/cdesc-RDoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/GitHub/cdesc-GitHub.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/GitHub/commit_sha1-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/GitHub/github_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/GitHub/have_git%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/GitHub/path_relative_to_repository-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/GitHub/path_to_git_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/GitHub/repository_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Helpers/cdesc-Helpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Helpers/each_letter_group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Helpers/group_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/append_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/cdesc-Merge.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/check_directories-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/copy_docs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/copy_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/extract_index_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/generate_index_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/merge_search_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/merge_tree-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/parse_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/setup_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Merge/setup_output_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Templatable/cdesc-Templatable.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Templatable/eval_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Templatable/include_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/Templatable/render_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/SDoc/cdesc-SDoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/merge/page-index_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/page-_context_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/page-_head_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/page-class_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/page-file_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/page-index_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/page-search_index_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/css/page-github_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/css/page-main_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/css/page-panel_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/css/page-reset_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/js/page-highlight_pack_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/js/page-jquery-1_3_2_min_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/js/page-jquery-effect_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/js/page-main_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/js/page-searchdoc_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/rails/resources/panel/page-index_html.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/page-_context_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/page-_head_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/page-class_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/page-file_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/page-index_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/page-search_index_rhtml.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/css/page-github_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/css/page-main_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/css/page-panel_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/css/page-reset_css.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/js/page-highlight_pack_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/js/page-jquery-1_3_2_min_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/js/page-jquery-effect_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/js/page-main_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/js/page-searchdoc_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/lib/rdoc/generator/template/sdoc/resources/panel/page-index_html.ri
/usr/lib64/ruby/gems/2.2.0/doc/sdoc-0.4.1/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/Gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/bin/sdoc
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/bin/sdoc-merge
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/discover.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/merge/index.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/_context.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/_head.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/class.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/file.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/index.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/apple-touch-icon.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/css/github.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/css/main.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/css/panel.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/css/reset.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/favicon.ico
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/i/arrows.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/i/results_bg.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/i/tree_bg.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/js/highlight.pack.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/js/jquery-1.3.2.min.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/js/jquery-effect.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/js/main.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/js/searchdoc.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/resources/panel/index.html
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/rails/search_index.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/_context.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/_head.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/class.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/file.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/index.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/apple-touch-icon.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/css/github.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/css/main.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/css/panel.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/css/reset.css
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/favicon.ico
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/i/arrows.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/i/results_bg.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/i/tree_bg.png
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/js/highlight.pack.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/js/jquery-1.3.2.min.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/js/jquery-effect.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/js/main.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/js/searchdoc.js
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/resources/panel/index.html
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/rdoc/generator/template/sdoc/search_index.rhtml
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/github.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/merge.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/templatable.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/sdoc.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/spec/rdoc_generator_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/sdoc-0.4.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/sdoc-0.4.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/sdoc
/usr/bin/sdoc-merge
